### ISSUE TITLE
add "(" to permitted functions?

### ISSUE THREAD

**Issue by tslumley** [edgararuiz/tidypredict#7]
The model
```
m <- glm(low~(age+lwt)*(race+smoke),data=MASS::birthwt,family=binomial)
parse_model(m)
```
is equivalent to 
```
m <- glm(low~age*race+lwt*race+age*smoke+lwt*smoke,data=MASS::birthwt,family=binomial)
parse_model(m)
```

The first version gives 
```
Error: Functions inside the formula are not supported. Functions detected `(`
```

It looks (on a superficial examination) as though just adding `(` to the list of allowed functions is enough to make the first version work.

**Comment by edgararuiz** [comment]
@tslumley - Thanks for the great suggestions!

**Comment by tslumley** [comment]
If you want to see what I'm using it for: https://github.com/tslumley/dbglm

**Comment by edgararuiz** [comment]
This is really cool! Need any help with it?
