### ISSUE TITLE
Log links?

### ISSUE THREAD

**Issue by tslumley** [edgararuiz/tidypredict#9]
Since I'm having such success with this so far:

In `te_fit_glm` you could support the log link (the most important one not already supported) with

```
  if ( link == "log") {
    assigned <- 1
    fit <- expr(exp(!! fit))
  }
```

Also, for the identity link it isn't necessary to check that you have `family=gaussian()`. The predictions will still work for any other family -- it's just intervals that don't, and you have a test for that in `te_interval_glm`

In fact, even for the logit link it's worth allowing family=quasibinomial, for modelling proportions between 0 and 1 that aren't probabilities, such as tip as a %age of payment in the big NYC taxi dataset.

**Comment by edgararuiz** [comment]
Yup, I'll update that tonight.  Thanks!
